// Khởi tạo ACTION cho redux
const ACTIONS = {
    LOGIN: 'LOGIN',
    GET_TOKEN: 'GET_TOKEN',
    GET_USER: 'GET_USER',
    GET_ADDRESS: 'GET_ADDRESS',
    GET_ALL_USERS: 'GET_ALL_USERS',
    GET_ALL_STORES: 'GET_ALL_STORES',
    GET_STORES: 'GET_STORES',
    GET_MENU: 'GET_MENU',
    GET_ALL_MENU: 'GET_ALL_MENU',
    GET_CART: 'GET_CART',
    COUNT_ACCOUNT: 'COUNT_ACCOUNT',
    COUNT_STORE: 'COUNT_STORE',
    COUNT_STORES: 'COUNT_STORES',
    COUNT_ITEMS: 'COUNT_ITEMS',
    STORE: 'STORE',
    GET_SHPPIER:'GET_SHIPPER',
    RESULT_SEARCH: 'RESULT_SEARCH',
    RATE: 'RATE',
    GET_ORDER: 'GET_ORDER',
    PROCESS: 'PROCESS',
    REQ_ORDER: 'REQ_ORDER',
    GET_ORDER_CANNEL: 'GET_ORDER_CANNEL',
    GET_ORDER_SUCC: 'GET_ORDER_SUCC'

}
export default ACTIONS